// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWfLLU2UX2Xx2BOaXCwGQyxGDK7K5qWLM',
    appId: '1:28758149488:web:3e234a0bef7d804ac3e7b5',
    messagingSenderId: '28758149488',
    projectId: 'suplementos-2fbbd',
    authDomain: 'suplementos-2fbbd.firebaseapp.com',
    storageBucket: 'suplementos-2fbbd.appspot.com',
    measurementId: 'G-87XTWMXPGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4mo8MsNHzj5t6WOzRwtdBtJCuflkhiI',
    appId: '1:28758149488:android:85b5fe0857eada47c3e7b5',
    messagingSenderId: '28758149488',
    projectId: 'suplementos-2fbbd',
    storageBucket: 'suplementos-2fbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcegIGdmCSxD8h5o0C-e2q1VFdcF07Jtg',
    appId: '1:28758149488:ios:5cb41d7aac264d62c3e7b5',
    messagingSenderId: '28758149488',
    projectId: 'suplementos-2fbbd',
    storageBucket: 'suplementos-2fbbd.appspot.com',
    iosClientId: '28758149488-qp314v8g74tl7k4g7ctjaq8afehok89d.apps.googleusercontent.com',
    iosBundleId: 'com.example.suplementos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcegIGdmCSxD8h5o0C-e2q1VFdcF07Jtg',
    appId: '1:28758149488:ios:5cb41d7aac264d62c3e7b5',
    messagingSenderId: '28758149488',
    projectId: 'suplementos-2fbbd',
    storageBucket: 'suplementos-2fbbd.appspot.com',
    iosClientId: '28758149488-qp314v8g74tl7k4g7ctjaq8afehok89d.apps.googleusercontent.com',
    iosBundleId: 'com.example.suplementos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWfLLU2UX2Xx2BOaXCwGQyxGDK7K5qWLM',
    appId: '1:28758149488:web:6ac9203b85132008c3e7b5',
    messagingSenderId: '28758149488',
    projectId: 'suplementos-2fbbd',
    authDomain: 'suplementos-2fbbd.firebaseapp.com',
    storageBucket: 'suplementos-2fbbd.appspot.com',
    measurementId: 'G-JS4R0S2PEP',
  );
}
